jdbc.driverClassName = com.mysql.jdbc.Driver
jdbc.url = jdbc:mysql://manuscriptlink.cj32dioabu7u.ap-northeast-2.rds.amazonaws.com:3306/egypt?zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&useLegacyDatetimeCode=false&serverTimezone=GMT
jdbc.username = mluser
jdbc.password = th!nk0nweb!


super.test=false
super.password = 1234

file.maxSize=104857600
file.uploadPath=/usr/share/egypt/upload

env.text=This is prod