jdbc.driverClassName = com.mysql.jdbc.Driver
jdbc.url = jdbc:mysql://localhost:3306/egypt?characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8
jdbc.username = root
jdbc.password = \uBE44\uBC00\uBC88\uD638


super.test=false
super.password = 1234

env.text=This is prod